### ISSUE TITLE
Running django dev environment is not reacheable

### ISSUE THREAD

**Issue by ipostolaki** [ipostolaki/Comeo#3]
Running django dev environment is not reacheable after the first `make run`.
At the same time RabbitMQ and Neo4j web interfaces are accessible.

**Comment by ipostolaki** [comment]
The assumption is that initial migrations were not applied.
There is an automated step to execute migrations on every run of the staging environment.
But, the same is not true for the development environment.

So it is necessary to run migrations inside of the running django container.
The simplest way to do that is `make migrate` in the project folder.

(At the moment some details about the initial start are not described in the Readme file)

@stephendwolff, I hope that'll help you solve described issue.

**Comment by ipostolaki** [comment]
There is another possible reason of this issue. The current revision of `env-template` file does not contain key `DJANGO_SETTINGS_MODULE`.
(I assume you have used `env-template` to create `dev.env` file)

I think I will add new makefile target – `make init`. This will ensure successful initialization of the development environment right after the first repository checkout.
Will let you know, when this change will be pushed.

**Comment by ipostolaki** [comment]
I have slightly modified dev environment infrastructure files.
I think that latest commit should fix the discussed issue.
577c56ad4955455187d33b77e1105a335882e00a

If after pulling, there will be any conflicts, maybe it will be easier to "hard reset" the repo.

@stephendwolff Thanks for your trial to run this system. It helped to identify and fix some things.

Soon I will add some additional documentation about available [make targets](https://github.com/ipostolaki/Comeo/blob/master/tools/Makefile-base) and other things. It will clarify how to work with development environment.

**Comment by stephendwolff** [comment]
Thanks @ipostolaki, I can confirm it all starts up fine now.

**Comment by ipostolaki** [comment]
Issue is resolved. If you will notice any code in this project which should be better, please let me know. I will truly appreciate it.
(The next planned improvement is refactoring of the views, to use CBV's where applicable).
